# Sandbox for simulating bivariate Guassian random fields

In [1]:
%load_ext autoreload
%autoreload 2

import sys
sys.path.insert(0, "../src")

In [2]:
import numpy as np
import pandas as pd
import xarray as xr
from cmcrameri import cm

import model
import sim
import plot

%matplotlib inline

In [19]:
g = sim.CartesianGrid(xcount=2, ycount=2)
g.coords

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [20]:
g.dist

array([[0.        , 1.        , 1.        , 1.41421356],
       [1.        , 0.        , 1.41421356, 1.        ],
       [1.        , 1.41421356, 0.        , 1.        ],
       [1.41421356, 1.        , 1.        , 0.        ]])

In [23]:
mod = model.MultivariateMatern()
S = sim.Sim(mod, g)
S.cmat

array([[1.        , 0.99999401, 0.99999401, 0.99998804, 0.        ,
        0.        , 0.        , 0.        ],
       [0.99999401, 1.        , 0.99998804, 0.99999401, 0.        ,
        0.        , 0.        , 0.        ],
       [0.99999401, 0.99998804, 1.        , 0.99999401, 0.        ,
        0.        , 0.        , 0.        ],
       [0.99998804, 0.99999401, 0.99999401, 1.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 1.        ,
        0.99999401, 0.99999401, 0.99998804],
       [0.        , 0.        , 0.        , 0.        , 0.99999401,
        1.        , 0.99998804, 0.99999401],
       [0.        , 0.        , 0.        , 0.        , 0.99999401,
        0.99998804, 1.        , 0.99999401],
       [0.        , 0.        , 0.        , 0.        , 0.99998804,
        0.99999401, 0.99999401, 1.        ]])